# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal      

    - name: Get version
      id: get_version
      shell: pwsh
      run: |
        $version = (Select-String -Path 'BrightXaml.Extensibility/BrightXaml.Extensibility.csproj' -Pattern '<Version>(.*?)</Version>').Matches[0].Groups[1].Value
        echo "##vso[task.setvariable variable=version]$version"

    - name: Rename VSIX file for push (BrightXaml)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: pwsh
      run: |
        $version = '${{ env.version }}'
        $vsix_file = Get-ChildItem -Path . -Filter *.vsix
        $new_name = "BrightXaml_$version.vsix"
        Rename-Item -Path $vsix_file.FullName -NewName $new_name

    - name: Rename VSIX file for PR (BrightXaml)
      if: github.event_name == 'pull_request'
      shell: pwsh
      run: |
        $version = '${{ env.version }}'
        $vsix_file = Get-ChildItem -Path . -Filter *.vsix
        $pr_id = '${{ github.event.number }}'
        $new_name = "BrightXaml_PR_${pr_id}.vsix"
        Rename-Item -Path $vsix_file.FullName -NewName $new_name

    - name: Upload VSIX artifact (BrightXaml)
      uses: actions/upload-artifact@v3
      with:
        name: vsix-artifact
        path: './BrightXaml_*.vsix'